name: VLESS Service and IP Reporting

on:
  push:
    branches:
      - main  # Run on push to main branch
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes for both IP reporting and VLESS service check
  workflow_dispatch:

jobs:
  monitor_vless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full repository is checked out

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the required Python version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install the necessary dependencies

      - name: Execute Python script to monitor VLESS service and report public IP
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 vless/check_vless.py  # Run your Python script
